# Generated by Django 3.0.5 on 2020-04-23 17:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_newcoach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcoach',
            name='birth',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='newcoach',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Indoor', 'Indoor Cycling'), ('Yoga', 'Yoga'), ('Funcional', 'Funcional'), ('Hiper', 'Hipertrofia'), ('Fat', 'Quema de Grasa'), ('Meditacion', 'Meditacion'), ('Nutricion', 'Nutricion')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='newcoach',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='newcoach',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcoach',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newcoach',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='pics/profile_pics'),
        ),
    ]
