# Generated by Django 3.0.5 on 2020-04-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200423_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevideos',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='newcoach',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
